name: listing_directory_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

#TODO: CHANGE THE VERSION TO 1.0.0 ON YOUR FIRST RELEASE(OPTIONAL)
version: 1.0.5+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # FIREBASE
  firebase_analytics: 6.3.0
  firebase_messaging: ^7.0.3
  firebase_dynamic_links: 0.6.3
  cloud_firestore: 0.14.4
  firebase_core : 0.5.3

  # AUTHENTICATION
  google_sign_in: ^4.5.6
  flutter_facebook_auth: ^2.0.0+1
  sign_in_with_apple: ^2.5.4
  apple_sign_in: ^0.1.0

  # LOCALE
  easy_localization: any

  # UI CUSTOMIZATION
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+3
  font_awesome_flutter: ^8.10.1
  flutter_rating_bar: ^3.2.0+1

  # MAP
  google_maps_flutter: ^1.0.6

  # IMAGE TOOLS
  flutter_swiper: ^1.1.6
  flutter_slidable: ^0.5.7
  multi_image_picker: ^4.6.5
  carousel_slider: ^2.3.1
  cached_network_image: ^2.5.0
  flutter_image_compress: 0.7.0
  #  image_picker: ^0.6.7+21

  # PAYMENTS

  # UTILS
  http: ^0.12.2
  html: ^0.14.0+4
  easy_debounce: ^1.0.2
  location: ^3.1.0
  pull_to_refresh: ^1.6.4
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  dio: ^3.0.10
  fluttertoast: ^7.1.6
  auto_size_text: ^2.1.0
  flutter_native_admob: ^2.1.0+3
  uuid: 2.2.2
  share: ^0.6.5+4
  webview_flutter: ^1.0.7
  http_auth: ^0.3.1
  flutter_html: 1.2.0
  flutter_svg: ^0.19.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/logo/in-app-logo.png
    - assets/translations/

# TODO: RUN THIS COMMAND IN TERMINAL TO CREATE YOUR APP ICON: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  # TODO: CHANGE THIS PATH TO YOUR LOGO IMAGE PATH. OR JUST RENAME YOUR IMAGE FILE TO logo.png
  image_path: "assets/logo/in-app-logo.png"